# Generated by Django 5.2.14 on 2026-05-23 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rooms", "Rooms"),
                            ("pg", "PG"),
                            ("flats", "Flats"),
                            ("houses", "Houses"),
                            ("hostels", "Hostels"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
                ("city", models.CharField(default="Unknown", max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="properties/")),
                ("available", models.BooleanField(default=True)),
                ("wifi", models.BooleanField(default=False)),
                ("parking", models.BooleanField(default=False)),
                ("food", models.BooleanField(default=False)),
                ("ac", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
